import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;

public class AmebaDiv2 {
	public int simulate(int[] X, int A) {
		for (int i : X) {
			if (A == i) {
				A += i;
			}
		}
		return A;
	}

	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit-pf 2.3.0
	private static boolean KawigiEdit_RunTest(int testNum, int[] p0, int p1,
			boolean hasAnswer, int p2) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p0[i]);
		}
		System.out.print("}" + "," + p1);
		System.out.println("]");
		AmebaDiv2 obj;
		int answer;
		obj = new AmebaDiv2();
		long startTime = System.currentTimeMillis();
		answer = obj.simulate(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0
				+ " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p2);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p2;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}

	public static void main(String[] args) {
		boolean all_right;
		boolean disabled;
		boolean tests_disabled;
		all_right = true;
		tests_disabled = false;

		int[] p0;
		int p1;
		int p2;

		// ----- test 0 -----
		disabled = false;
		p0 = new int[] { 2, 1, 3, 1, 2 };
		p1 = 1;
		p2 = 4;
		all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, true, p2))
				&& all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 1 -----
		disabled = false;
		p0 = new int[] { 1, 4, 9, 16, 25, 36, 49 };
		p1 = 10;
		p2 = 10;
		all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, true, p2))
				&& all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 2 -----
		disabled = false;
		p0 = new int[] { 1, 2, 4, 8, 16, 32, 64, 128, 256, 1024, 2048 };
		p1 = 1;
		p2 = 512;
		all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, true, p2))
				&& all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 3 -----
		disabled = false;
		p0 = new int[] { 817, 832, 817, 832, 126, 817, 63, 63, 126, 817, 832,
				287, 823, 817, 574 };
		p1 = 63;
		p2 = 252;
		all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, true, p2))
				&& all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		if (all_right) {
			if (tests_disabled) {
				System.out
						.println("You're a stud (but some test cases were disabled)!");
			} else {
				System.out.println("You're a stud (at least on given cases)!");
			}
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}

// Powered by KawigiEdit-pf 2.3.0!
