import math,string,itertools,fractions,heapq,collections,re,array,bisect,random

class BigFatInteger2:
    def isDivisible(self, A, B, C, D):
        dictA=getMap(A)
        dictC=getMap(C)
        isOK=True
        for key in dictC:
            if key in dictA:
               left=dictA[key]*B
                   right=dictC[key]*D
                   if (left<right)
                    isOK=False
                    break
                else:
                    isOK=False
                    break
        if (isOK)
            return "divisible"
        return "not divisible"


    #素因数分解を求める
    def getMap(A):
        dict={}
        i=2
        tmp=A
        while i*i<=A:
            count=0
            while tmp>1
                if (tmp % i==0):
                    tmp/=i
                    count+=1
                else:
                    break;
            if (count>0):
                dict[i]=count
            i++;
        if(tmp>1):
            dict[tmp]=1
        return dict 
        

# BEGIN KAWIGIEDIT TESTING
# Generated by KawigiEdit-pf 2.3.0
import sys
import time
def KawigiEdit_RunTest(testNum, p0, p1, p2, p3, hasAnswer, p4):
    sys.stdout.write(str("Test ") + str(testNum) + str(": [") + str(p0) + str(",") + str(p1) + str(",") + str(p2) + str(",") + str(p3))
    print(str("]"))
    obj = BigFatInteger2()
    startTime = time.clock()
    answer = obj.isDivisible(p0, p1, p2, p3)
    endTime = time.clock()
    res = True
    print(str("Time: ") + str((endTime - startTime)) + str(" seconds"))
    if (hasAnswer):
        print(str("Desired answer:"))
        print(str("\t") + str("\"") + str(p4) + str("\""))
    
    print(str("Your answer:"))
    print(str("\t") + str("\"") + str(answer) + str("\""))
    if (hasAnswer):
        res = answer == p4
    
    if (not res):
        print(str("DOESN'T MATCH!!!!"))
    elif ((endTime - startTime) >= 2):
        print(str("FAIL the timeout"))
        res = False
    elif (hasAnswer):
        print(str("Match :-)"))
    else:
        print(str("OK, but is it right?"))
    
    print(str(""))
    return res

all_right = True
tests_disabled = False


if (all_right):
    if (tests_disabled):
        print(str("You're a stud (but some test cases were disabled)!"))
    else:
        print(str("You're a stud (at least on given cases)!"))
    
else:
    print(str("Some of the test cases had errors."))

# END KAWIGIEDIT TESTING
#Powered by KawigiEdit-pf 2.3.0!
