import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;

public class ElephantDrinkingEasy
{
	public int maxElephants(String[] map)
	{
		int count = 0;
		for (int i = 0; i < map.length; i++) {
			for (int j = 0; j < map.length; j++) {
				if (map[i].charAt(j) == 'Y') {
					if (check(map, i, j)) {
						count++;
					}
				}
			}
		}
		return count;
	}

	boolean check(String[] map, int i, int j) {
		boolean hit;
		hit = false;
		for (int i2 = i + 1; i2 < map.length; i2++) {
			if (map[i2].charAt(j) == 'Y') {
				hit = true;
			}
		}
		if (!hit) {
			return true;
		}
		hit = false;
		for (int i2 = i - 1; i2 >= 0; i2--) {
			if (map[i2].charAt(j) == 'Y') {
				hit = true;
			}
		}
		if (!hit) {
			return true;
		}
		hit = false;
		for (int i2 = j + 1; i2 < map[i].length(); i2++) {
			if (map[i].charAt(i2) == 'Y') {
				hit = true;
			}
		}
		if (!hit) {
			return true;
		}
		hit = false;
		for (int i2 = j - 1; i2 >= 0; i2--) {
			if (map[i].charAt(i2) == 'Y') {
				hit = true;
			}
		}
		if (!hit) {
			return true;
		}
		return false;
	}

	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit-pf 2.3.0
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, int p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		ElephantDrinkingEasy obj;
		int answer;
		obj = new ElephantDrinkingEasy();
		long startTime = System.currentTimeMillis();
		answer = obj.maxElephants(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			res = answer == p1;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
			if (hasAnswer) {
				System.out.println("Desired answer:");
				System.out.println("\t" + p1);
			}
			System.out.println("Your answer:");
			System.out.println("\t" + answer);
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}

	public static void main(String[] args) {
		boolean all_right;
		boolean disabled;
		boolean tests_disabled;
		all_right = true;
		tests_disabled = false;

		String[] p0;
		int p1;

		// ----- test 0 -----
		disabled = false;
		p0 = new String[] { "NNNNN", "NNYYN", "NYNNN", "NNYNN", "NNNNN" };
		p1 = 4;
		all_right = (disabled || KawigiEdit_RunTest(0, p0, true, p1)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 1 -----
		disabled = false;
		p0 = new String[] { "YYY", "YYY", "YYY" };
		p1 = 8;
		all_right = (disabled || KawigiEdit_RunTest(1, p0, true, p1)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 2 -----
		disabled = false;
		p0 = new String[] { "YNYN", "NNYY", "YYNN", "YYYY" };
		p1 = 10;
		all_right = (disabled || KawigiEdit_RunTest(2, p0, true, p1)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 3 -----
		disabled = false;
		p0 = new String[] { "YNYN", "YNYY", "YYNN", "YYYY" };
		p1 = 10;
		all_right = (disabled || KawigiEdit_RunTest(3, p0, true, p1)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 4 -----
		disabled = false;
		p0 = new String[] { "YYNYN", "NYNNY", "YNYNN", "YYNYY", "YYNNN" };
		p1 = 12;
		all_right = (disabled || KawigiEdit_RunTest(4, p0, true, p1)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 5 -----
		disabled = false;
		p0 = new String[] { "YYNYN", "NYNYY", "YNYYN", "YYNYY", "YYNNN" };
		p1 = 13;
		all_right = (disabled || KawigiEdit_RunTest(5, p0, true, p1)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 6 -----
		disabled = false;
		p0 = new String[] { "NN", "NN" };
		p1 = 0;
		all_right = (disabled || KawigiEdit_RunTest(6, p0, true, p1)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		if (all_right) {
			if (tests_disabled) {
				System.out.println("You're a stud (but some test cases were disabled)!");
			} else {
				System.out.println("You're a stud (at least on given cases)!");
			}
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}

// Powered by KawigiEdit-pf 2.3.0!
