import math,string,itertools,fractions,heapq,collections,re,array,bisect,random

class EllysNumberGuessing:
    def getNumber(self, guesses, answers):       
        evidence=[0,0]
        hitHigh=hitLow=False
        if (guesses[0]+answers[0]<=1000000000):
            evidence[0]=(guesses[0]+answers[0])
            hitHigh=True
        if (guesses[0]-answers[0]>0):
            evidence[1]=(guesses[0]-answers[0])            
            hitLow=True            
        for i in range(1,len(guesses)):
            if (hitHigh):
                hitHigh=((evidence[0]==guesses[i]+answers[i]) or (evidence[0]==guesses[i]-answers[i]))
            if (hitLow):
                hitLow=((evidence[1]==guesses[i]+answers[i]) or (evidence[1]==guesses[i]-answers[i]))
        if (not hitHigh and not hitLow):
            return -2
        if (hitHigh and hitLow):
            return -1
        if (hitHigh):
            return evidence[0]
        return evidence[1]

# BEGIN KAWIGIEDIT TESTING
# Generated by KawigiEdit-pf 2.3.0
import sys
import time
def KawigiEdit_RunTest(testNum, p0, p1, hasAnswer, p2):
    sys.stdout.write(str("Test ") + str(testNum) + str(": [") + str("{"))
    for i in range(len(p0)):
        if (i > 0):
            sys.stdout.write(str(","))
        
        sys.stdout.write(str(p0[i]))
    
    sys.stdout.write(str("}") + str(",") + str("{"))
    for i in range(len(p1)):
        if (i > 0):
            sys.stdout.write(str(","))
        
        sys.stdout.write(str(p1[i]))
    
    sys.stdout.write(str("}"))
    print(str("]"))
    obj = EllysNumberGuessing()
    startTime = time.clock()
    answer = obj.getNumber(p0, p1)
    endTime = time.clock()
    res = True
    print(str("Time: ") + str((endTime - startTime)) + str(" seconds"))
    if (hasAnswer):
        print(str("Desired answer:"))
        print(str("\t") + str(p2))
    
    print(str("Your answer:"))
    print(str("\t") + str(answer))
    if (hasAnswer):
        res = answer == p2
    
    if (not res):
        print(str("DOESN'T MATCH!!!!"))
    elif ((endTime - startTime) >= 2):
        print(str("FAIL the timeout"))
        res = False
    elif (hasAnswer):
        print(str("Match :-)"))
    else:
        print(str("OK, but is it right?"))
    
    print(str(""))
    return res

all_right = True
tests_disabled = False


# ----- test 0 -----
disabled = False
p0 = (600,594)
p1 = (6,12)
p2 = 606
all_right = (disabled or KawigiEdit_RunTest(0, p0, p1, True, p2) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 1 -----
disabled = False
p0 = (100,50,34,40)
p1 = (58,8,8,2)
p2 = 42
all_right = (disabled or KawigiEdit_RunTest(1, p0, p1, True, p2) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 2 -----
disabled = False
p0 = (500000,600000,700000)
p1 = (120013,220013,79987)
p2 = -2
all_right = (disabled or KawigiEdit_RunTest(2, p0, p1, True, p2) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 3 -----
disabled = False
p0 = (500000000,)
p1 = (133742666,)
p2 = -1
all_right = (disabled or KawigiEdit_RunTest(3, p0, p1, True, p2) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 4 -----
disabled = False
p0 = (76938260,523164588,14196746,296286419,535893832,41243148,364561227,270003278,472017422,367932361,395758413,301278456,186276934,316343129,336557549,52536121,98343562,356769915,89249181,335191879)
p1 = (466274085,20047757,529015599,246925926,7318513,501969197,178651118,273209067,71194923,175279984,147453932,241933889,356935411,226869216,206654796,490676224,444868783,186442430,453963164,208020466)
p2 = 543212345
all_right = (disabled or KawigiEdit_RunTest(4, p0, p1, True, p2) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 5 -----
disabled = False
p0 = (42,)
p1 = (42,)
p2 = 84
all_right = (disabled or KawigiEdit_RunTest(5, p0, p1, True, p2) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 6 -----
disabled = False
p0 = (999900000,)
p1 = (100001,)
p2 = 999799999
all_right = (disabled or KawigiEdit_RunTest(6, p0, p1, True, p2) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

if (all_right):
    if (tests_disabled):
        print(str("You're a stud (but some test cases were disabled)!"))
    else:
        print(str("You're a stud (at least on given cases)!"))
    
else:
    print(str("Some of the test cases had errors."))

# END KAWIGIEDIT TESTING
#Powered by KawigiEdit-pf 2.3.0!
