import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;

import org.omg.PortableInterceptor.INACTIVE;

public class MinimumSquareEasy {
	public long minArea(int[] x, int[] y) {
		long minArea = Long.MAX_VALUE;
		for (int i = 0; i < y.length; i++) {
			for (int j = i + 1; j < y.length; j++) {
				long minX, minY, maxX, maxY;
				minX = minY = Long.MAX_VALUE;
				maxX = maxY = Long.MIN_VALUE;
				for (int k = 0; k < y.length; k++) {
					if (k == i || k == j)
						continue;
					minX = Math.min(minX, x[k]);
					minY = Math.min(minY, y[k]);
					maxX = Math.max(maxX, x[k]);
					maxY = Math.max(maxY, y[k]);
				}
				long maxLen = Math.max(2 + (maxX - minX), (2 + (maxY - minY)));
				long area = maxLen * maxLen;
				minArea = Math.min(area, minArea);
			}
		}
		return minArea;
	}

	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit-pf 2.3.0
	private static boolean KawigiEdit_RunTest(int testNum, int[] p0, int[] p1, boolean hasAnswer, long p2) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p0[i]);
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p1[i]);
		}
		System.out.print("}");
		System.out.println("]");
		MinimumSquareEasy obj;
		long answer;
		obj = new MinimumSquareEasy();
		long startTime = System.currentTimeMillis();
		answer = obj.minArea(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p2);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p2;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		boolean disabled;
		boolean tests_disabled;
		all_right = true;
		tests_disabled = false;
		
		int[] p0;
		int[] p1;
		long p2;
		
		// ----- test 0 -----
		disabled = false;
		p0 = new int[]{0,1,2};
		p1 = new int[]{0,1,5};
		p2 = 4L;
		all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 1 -----
		disabled = false;
		p0 = new int[]{-1,-1,0,2,0};
		p1 = new int[]{-2,-1,0,-1,-2};
		p2 = 9L;
		all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 2 -----
		disabled = false;
		p0 = new int[]{1000000000,-1000000000,1000000000,-1000000000};
		p1 = new int[]{1000000000,1000000000,-1000000000,-1000000000};
		p2 = 4000000008000000004L;
		all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 3 -----
		disabled = false;
		p0 = new int[]{93,34,12,-11,-7,-21,51,-22,59,74,-19,29,-56,-95,-96,9,44,-37,-54,-21};
		p1 = new int[]{64,12,-43,20,55,74,-20,-54,24,20,-18,77,86,22,47,-24,-33,-57,5,7};
		p2 = 22801L;
		all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 4 -----
		disabled = false;
		p0 = new int[]{0,0,1,1,1000};
		p1 = new int[]{0,1,0,1,0};
		p2 = 9L;
		all_right = (disabled || KawigiEdit_RunTest(4, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		if (all_right) {
			if (tests_disabled) {
				System.out.println("You're a stud (but some test cases were disabled)!");
			} else {
				System.out.println("You're a stud (at least on given cases)!");
			}
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}

// Powered by KawigiEdit-pf 2.3.0!
