import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;

public class PowerOfThreeEasy {	
	public String ableToGet(int x, int y) {
		boolean result = search(x, y, 1);
		if (result) {
			return "Possible";
		}
		return "Impossible";
	}

	public boolean search(int x, int y, int num) {
		if (x == 0 && y == 0) {
			return true;
		}
		if (x > 0) {
			boolean result = search(x - num, y, num * 3);
			if (result) {
				return true;
			}
		}
		if (y > 0) {
			boolean result = search(x, y - num, num * 3);
			if (result) {
				return true;
			}
		}
		return false;
	}

	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit-pf 2.3.0
	private static boolean KawigiEdit_RunTest(int testNum, int p0, int p1,
			boolean hasAnswer, String p2) {
		System.out.print("Test " + testNum + ": [" + p0 + "," + p1);
		System.out.println("]");
		PowerOfThreeEasy obj;
		String answer;
		obj = new PowerOfThreeEasy();
		long startTime = System.currentTimeMillis();
		answer = obj.ableToGet(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0
				+ " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p2 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p2);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}

	public static void main(String[] args) {
		boolean all_right;
		boolean disabled;
		boolean tests_disabled;
		all_right = true;
		tests_disabled = false;

		int p0;
		int p1;
		String p2;

		// ----- test 0 -----
		disabled = false;
		p0 = 1;
		p1 = 3;
		p2 = "Possible";
		all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, true, p2))
				&& all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 1 -----
		disabled = false;
		p0 = 1;
		p1 = 1;
		p2 = "Impossible";
		all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, true, p2))
				&& all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 2 -----
		disabled = false;
		p0 = 3;
		p1 = 0;
		p2 = "Impossible";
		all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, true, p2))
				&& all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 3 -----
		disabled = false;
		p0 = 1;
		p1 = 9;
		p2 = "Impossible";
		all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, true, p2))
				&& all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 4 -----
		disabled = false;
		p0 = 3;
		p1 = 10;
		p2 = "Possible";
		all_right = (disabled || KawigiEdit_RunTest(4, p0, p1, true, p2))
				&& all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 5 -----
		disabled = false;
		p0 = 1093;
		p1 = 2187;
		p2 = "Possible";
		all_right = (disabled || KawigiEdit_RunTest(5, p0, p1, true, p2))
				&& all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 6 -----
		disabled = false;
		p0 = 0;
		p1 = 0;
		p2 = "Possible";
		all_right = (disabled || KawigiEdit_RunTest(6, p0, p1, true, p2))
				&& all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		if (all_right) {
			if (tests_disabled) {
				System.out
						.println("You're a stud (but some test cases were disabled)!");
			} else {
				System.out.println("You're a stud (at least on given cases)!");
			}
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}

// Powered by KawigiEdit-pf 2.3.0!
