
public class Soccer
{
	public int maxPoints(int[] wins, int[] ties)
	{
		int max = 0;
		for (int i = 0; i < wins.length; i++) {
			int point = 3 * wins[i] + 1 * ties[i];
			max = Math.max(max, point);
		}
		return max;
	}

	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit-pfx 2.1.9
	private static boolean KawigiEdit_RunTest(int testNum, int[] p0, int[] p1, boolean hasAnswer, int p2) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p0[i]);
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p1[i]);
		}
		System.out.print("}");
		System.out.println("]");
		Soccer obj;
		int answer;
		obj = new Soccer();
		long startTime = System.currentTimeMillis();
		answer = obj.maxPoints(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p2);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p2;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}

	public static void main(String[] args) {
		boolean all_right;
		all_right = true;

		int[] p0;
		int[] p1;
		int p2;

		// ----- test 0 -----
		p0 = new int[] { 1, 4, 3, 0, 0 };
		p1 = new int[] { 3, 1, 5, 3, 1 };
		p2 = 14;
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------

		// ----- test 1 -----
		p0 = new int[] { 12, 45, 20, 17, 48, 0 };
		p1 = new int[] { 48, 10, 53, 94, 0, 100 };
		p2 = 145;
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------

		// ----- test 2 -----
		p0 = new int[] { 35, 0 };
		p1 = new int[] { 0, 76 };
		p2 = 105;
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------

		// ----- test 3 -----
		p0 = new int[] { 0, 0, 0, 0 };
		p1 = new int[] { 0, 0, 0, 0 };
		p2 = 0;
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------

		// ----- test 4 -----
		p0 = new int[] { 13, 79, 26, 73, 14, 89, 71, 37, 89, 71, 19, 59, 39 };
		p1 = new int[] { 88, 27, 5, 70, 84, 94, 20, 50, 2, 11, 31, 22, 50 };
		p2 = 361;
		all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
		// ------------------

		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
// Powered by KawigiEdit-pfx 2.1.9!
