import math, string, itertools, fractions, heapq, collections, re, array, bisect, random

class TheShuttles:
    def getLeastCost(self, cnt, baseCost, seatCost):
        mnCost = 100000000000000
        for seat in range(1, 100 + 1):
            cost = 0
            for c in cnt:
                number = int(math.ceil(1.0 * c / seat))
                cost += (baseCost + seat * seatCost) * number
            mnCost = min(mnCost, cost)
        return mnCost

# BEGIN KAWIGIEDIT TESTING
# Generated by KawigiEdit-pf 2.3.0
import sys
import time
def KawigiEdit_RunTest(testNum, p0, p1, p2, hasAnswer, p3):
	sys.stdout.write(str("Test ") + str(testNum) + str(": [") + str("{"))
	for i in range(len(p0)):
		if (i > 0):
			sys.stdout.write(str(","))
		
		sys.stdout.write(str(p0[i]))
	
	sys.stdout.write(str("}") + str(",") + str(p1) + str(",") + str(p2))
	print(str("]"))
	obj = TheShuttles()
	startTime = time.clock()
	answer = obj.getLeastCost(p0, p1, p2)
	endTime = time.clock()
	res = True
	print(str("Time: ") + str((endTime - startTime)) + str(" seconds"))
	if (hasAnswer):
		res = answer == p3
	
	if (not res):
		print(str("DOESN'T MATCH!!!!"))
		if (hasAnswer):
			print(str("Desired answer:"))
			print(str("\t") + str(p3))
		
		print(str("Your answer:"))
		print(str("\t") + str(answer))
	elif ((endTime - startTime) >= 2):
		print(str("FAIL the timeout"))
		res = False
	elif (hasAnswer):
		print(str("Match :-)"))
	else:
		print(str("OK, but is it right?"))
	
	print(str(""))
	return res

all_right = True
tests_disabled = False


# ----- test 0 -----
disabled = False
p0 = (9,)
p1 = 30
p2 = 5
p3 = 75
all_right = (disabled or KawigiEdit_RunTest(0, p0, p1, p2, True, p3)) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 1 -----
disabled = False
p0 = (9, 4)
p1 = 30
p2 = 5
p3 = 150
all_right = (disabled or KawigiEdit_RunTest(1, p0, p1, p2, True, p3)) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 2 -----
disabled = False
p0 = (9, 4)
p1 = 10
p2 = 5
p3 = 105
all_right = (disabled or KawigiEdit_RunTest(2, p0, p1, p2, True, p3)) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 3 -----
disabled = False
p0 = (51, 1, 77, 14, 17, 10, 80)
p1 = 32
p2 = 40
p3 = 12096
all_right = (disabled or KawigiEdit_RunTest(3, p0, p1, p2, True, p3)) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

if (all_right):
	if (tests_disabled):
		print(str("You're a stud (but some test cases were disabled)!"))
	else:
		print(str("You're a stud (at least on given cases)!"))
	
else:
	print(str("Some of the test cases had errors."))

# END KAWIGIEDIT TESTING
# Powered by KawigiEdit-pf 2.3.0!
