import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;

public class VocaloidsAndSongs
{
	public int count(int S, int gumi, int ia, int mayu)
	{
        long[][][][] dp=new long[S+1][S+1][S+1][S+1];
        long mod=1000000007;
        dp[0][0][0][0]=1;
        for (int i = 0; i < S; i++) {
            for (int a = 0; a <S ; a++) {
                for (int b = 0; b <S ; b++)
                    for (int c = 0; c < S; c++) {
                        long value = dp[i][a][b][c];
                        dp[i + 1][a][b][c] += value;
                        dp[i + 1][a + 1][b][c] %=mod;

                        dp[i + 1][a][b + 1][c] += value;
                        dp[i + 1][a][b + 1][c] %=mod;

                        dp[i + 1][a][b][c + 1] += value;
                        dp[i + 1][a][b][c + 1] %=mod;

                        dp[i + 1][a + 1][b + 1][c] += value;
                        dp[i + 1][a + 1][b + 1][c]%=mod;

                        dp[i + 1][a + 1][b][c + 1] += value;
                        dp[i + 1][a + 1][b][c + 1] %=mod;

                        dp[i + 1][a][b + 1][c + 1] += value;
                        dp[i + 1][a][b + 1][c + 1]%=mod;

                        dp[i + 1][a + 1][b + 1][c + 1] += value;
                        dp[i + 1][a + 1][b + 1][c + 1]%=mod;
                    }
            }
        }
        return (int)dp[S][gumi][ia][mayu];
    }

	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit-pf 2.3.0
	private static boolean KawigiEdit_RunTest(int testNum, int p0, int p1, int p2, int p3, boolean hasAnswer, int p4) {
		System.out.print("Test " + testNum + ": [" + p0 + "," + p1 + "," + p2 + "," + p3);
		System.out.println("]");
		VocaloidsAndSongs obj;
		int answer;
		obj = new VocaloidsAndSongs();
		long startTime = System.currentTimeMillis();
		answer = obj.count(p0, p1, p2, p3);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			res = answer == p4;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
			if (hasAnswer) {
				System.out.println("Desired answer:");
				System.out.println("\t" + p4);
			}
			System.out.println("Your answer:");
			System.out.println("\t" + answer);
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		boolean disabled;
		boolean tests_disabled;
		all_right = true;
		tests_disabled = false;
		
		int p0;
		int p1;
		int p2;
		int p3;
		int p4;
		
		// ----- test 0 -----
		disabled = false;
		p0 = 3;
		p1 = 1;
		p2 = 1;
		p3 = 1;
		p4 = 6;
		all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, p2, p3, true, p4) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 1 -----
		disabled = false;
		p0 = 3;
		p1 = 3;
		p2 = 1;
		p3 = 1;
		p4 = 9;
		all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, p2, p3, true, p4) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 2 -----
		disabled = false;
		p0 = 50;
		p1 = 10;
		p2 = 10;
		p3 = 10;
		p4 = 0;
		all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, p2, p3, true, p4) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 3 -----
		disabled = false;
		p0 = 18;
		p1 = 12;
		p2 = 8;
		p3 = 9;
		p4 = 81451692;
		all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, p2, p3, true, p4) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 4 -----
		disabled = false;
		p0 = 50;
		p1 = 25;
		p2 = 25;
		p3 = 25;
		p4 = 198591037;
		all_right = (disabled || KawigiEdit_RunTest(4, p0, p1, p2, p3, true, p4) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		if (all_right) {
			if (tests_disabled) {
				System.out.println("You're a stud (but some test cases were disabled)!");
			} else {
				System.out.println("You're a stud (at least on given cases)!");
			}
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}

// Powered by KawigiEdit-pf 2.3.0!
